image:
  repository: ghcr.io/tesddev/api-gateway
  tag: latest
replicaCount: 1
service:
  port: 80
  targetPort: 8000
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
env:
  authServiceUrl: "http://auth-service.platform.svc.cluster.local"
  notificationServiceUrl: "http://notification-service.platform.svc.cluster.local"
