image:
  repository: ghcr.io/tesddev/auth-service
  tag: latest
replicaCount: 1
service:
  port: 80
  targetPort: 8000
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
